# -*- coding: utf-8 -*-
from odoo.tests.common import TransactionCase

class TestDemandSensing(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
        cls.analytic = cls.env['supply.chain.analytics'].create({'name': 'Hub Demand Engine'})

    def test_01_c2m_propagation(self):
        """ Scenario 39: Demand-Sensing & Bullwhip Mitigation """
        self.analytic.action_c2m_demand_propagation()
        
        tasks = cls.env['project.task'].search([('name', 'ilike', 'C2M Auto-Quota')])
        self.assertTrue(tasks, "Planting task must be auto-generated by the Hub.")

