{
    'name': 'Precision Production IoT Integration',
    'summary': 'IoT Integration for Automatic Measurement Data Reading in Precision Production',
    'version': '1.1.1',
    'category': 'Manufacturing/IoT',
    'author': 'genin IT, 亘盈信息技术, jeffery <jeffery9@gmail.com>',
    'website': 'http://www.geninit.cn',
    'depends': [
        'base',
        'stock',
        'mrp',
        'agri_iot',
        'precision_production',
        'farm_agri_science',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/iot_device_views.xml',
        'views/iot_sensor_views.xml',
        'views/iot_reading_views.xml',
        'views/phase_execution_iot_views.xml',
        'views/precision_production_iot_menu.xml',
    ],
    'images': ['static/description/main_screenshot.png'],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
