from odoo import models, fields, api, _
from odoo.exceptions import ValidationError
import logging

_logger = logging.getLogger(__name__)


class InputVMIConfiguration(models.Model):
    """
    农资 VMI (供应商管理库存) 自动化 [US-09-14]
    """
    _name = 'input.vmi.configuration'
    _description = 'Input VMI Configuration for Supplier-Managed Inventory'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char('VMI Configuration Name', required=True)
    product_id = fields.Many2one('product.product', string='Agricultural Input',
                                domain=[('is_agri_input', '=', True)], required=True)
    supplier_id = fields.Many2one('res.partner', string='Supplier',
                                 domain=[('supplier_rank', '>', 0)], required=True)
    is_vmi_enabled = fields.Boolean('VMI Enabled', default=False)
    warning_level_qty = fields.Float('Warning Level Quantity', required=True,
                                   help='Quantity at which to warn supplier about low stock')
    danger_level_qty = fields.Float('Danger Level Quantity', required=True,
                                  help='Quantity at which to automatically trigger order')
    auto_reorder_qty = fields.Float('Auto Reorder Quantity', required=True,
                                  help='Quantity to automatically order when danger level reached')
    last_stock_update = fields.Datetime('Last Stock Update')
    current_stock_level = fields.Float('Current Stock Level')
    min_stock_level = fields.Float('Minimum Stock Level')
    max_stock_level = fields.Float('Maximum Stock Level')
    vmi_portal_access_url = fields.Char('VMI Portal Access URL',
                                       help='URL for supplier to access VMI portal')
    vmi_readings = fields.One2many('vmi.sensor.reading', 'vmi_config_id', string='VMI Sensor Readings')
    is_automated_reorder_enabled = fields.Boolean('Automated Reorder Enabled', default=False)

    def action_check_vmi_levels(self):
        """Check current stock levels against thresholds and trigger alerts if needed"""
        for config in self:
            if config.current_stock_level <= config.danger_level_qty and config.is_automated_reorder_enabled:
                config._trigger_automated_reorder()
            elif config.current_stock_level <= config.warning_level_qty:
                config._trigger_supplier_warning()

    def _trigger_automated_reorder(self):
        """Trigger automated reorder when danger level is reached"""
        # Create a purchase order automatically
        PurchaseOrder = self.env['purchase.order']
        PurchaseOrderLine = self.env['purchase.order.line']

        # Check if there's already a pending order for this product from this supplier
        existing_order = PurchaseOrder.search([
            ('partner_id', '=', self.supplier_id.id),
            ('state', 'in', ['draft', 'sent', 'to approve']),
            ('order_line.product_id', '=', self.product_id.id)
        ], limit=1)

        if not existing_order:
            # Create new purchase order
            po_vals = {
                'partner_id': self.supplier_id.id,
                'date_order': fields.Datetime.now(),
                'order_line': [(0, 0, {
                    'product_id': self.product_id.id,
                    'product_qty': self.auto_reorder_qty,
                    'price_unit': self.product_id.standard_price,
                    'name': self.product_id.name,
                })],
            }
            new_order = PurchaseOrder.create(po_vals)

            # Add a note about VMI auto-reorder
            new_order.message_post(
                body=_("This order was automatically generated by VMI system due to low stock level.")
            )

            _logger.info(f"VMI auto-reorder triggered for {self.product_id.name} for quantity {self.auto_reorder_qty}")

    def _trigger_supplier_warning(self):
        """Trigger warning to supplier about low stock"""
        self.env['mail.activity'].create({
            'res_model_id': self.env.ref('farm_supply.model_input_vmi_configuration').id,
            'res_id': self.id,
            'activity_type_id': self.env.ref('mail.mail_activity_data_todo').id,
            'summary': _('VMI Stock Level Warning for %s') % self.product_id.name,
            'note': _('Current stock level (%s) is at or below warning threshold (%s). Supplier %s should prepare for reorder.') % (
                self.current_stock_level, self.warning_level_qty, self.supplier_id.name
            ),
            'user_id': self.supplier_id.user_id.id if self.supplier_id.user_id else self.env.user.id,
            'date_deadline': fields.Date.add(fields.Date.today(), days=3),
        })


class VMISensorReading(models.Model):
    """
    VMI传感器读数 [US-09-14]
    """
    _name = 'vmi.sensor.reading'
    _description = 'VMI Sensor Reading for Inventory Tracking'
    _order = 'timestamp desc'

    vmi_config_id = fields.Many2one('input.vmi.configuration', string='VMI Configuration', required=True, ondelete='cascade')
    product_id = fields.Many2one('product.product', string='Product', related='vmi_config_id.product_id', store=True)
    sensor_id = fields.Char('Sensor ID', required=True, help='ID of the IoT sensor providing the reading')
    quantity = fields.Float('Quantity', required=True, help='Quantity reading from sensor')
    timestamp = fields.Datetime('Timestamp', required=True, default=fields.Datetime.now)
    temperature = fields.Float('Temperature (°C)')
    humidity = fields.Float('Humidity (%)')
    unit_of_measure = fields.Many2one('uom.uom', string='Unit of Measure')
    is_valid_reading = fields.Boolean('Is Valid Reading', default=True)
    notes = fields.Text('Notes')

    @api.model
    def create(self, vals):
        record = super().create(vals)
        # Update the parent VMI configuration with the latest reading
        if record.vmi_config_id:
            record.vmi_config_id.write({
                'current_stock_level': record.quantity,
                'last_stock_update': record.timestamp
            })
        return record


