from odoo import models, fields, api, _

class SupplyChainAnalytics(models.Model):
    _inherit = 'supply.chain.analytics'
    
    # [US-SCENARIO-39] Demand-Sensing & Bullwhip Mitigation
    def action_c2m_demand_propagation(self):
        """ Pulls POS trends and auto-generates planting quotas for smallholders """
        for analytic in self:
            # Mock pulling data
            analytic.message_post(body=_("Analyzing POS endpoints... Detected 15% surge in Organic Carrot demand."))
            
            # Generate planting task for cooperative
            # We assume farm_operation is available
            if 'project.task' in self.env:
                self.env['project.task'].create({
                    'name': 'C2M Auto-Quota: Plant 5000 units of Organic Carrots',
                    'description': 'Generated by Hub Demand-Sensing engine to prevent bullwhip effect.',
                })
                analytic.message_post(body=_("C2M Propagation: Dispatched planting quotas to cooperative nodes."))

